apiVersion: apps/v1
kind: Deployment
metadata:
  name: safra-deviceregistrationapi
  namespace: safra
spec:
  selector:
    matchLabels:
      app: safra-deviceregistrationapi
  template:
    metadata:
      labels:
        app: safra-deviceregistrationapi
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              value: svc-safra-postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: safra-db-credentials
                  key: password
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: safra-db-credentials
                  key: user
            - name: DEVICEREGISTRATION_USER_KEY
              valueFrom:
                secretKeyRef:
                  name: safra-api-userkey
                  key: userkey
          name: safra-deviceregistrationapi
          image: mmb2018/cn-deviceregister:v1.0.0
          resources:
            limits:
              memory: "128Mi"
          ports:
          - containerPort: 80
