apiVersion: v1
kind: Service
metadata:
  name: lb-safra-statisticsapi
  namespace: safra
spec:
  selector:
    app: safra-statisticsapi
  ports:
  - port: 32000
    protocol: TCP
    targetPort: 80
  type: LoadBalancer