kind: PersistentVolume
apiVersion: v1
metadata:
  name: safra-postgres-pv
  namespace: safra
  labels:
    type: local
    app: safra-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safra-postgres-claim0
  namespace: safra
  labels:
    app: safra-postgres
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
